import { rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const repositoryRoot = fileURLToPath(new URL('../', import.meta.url));

// Prevent an obsolete local POC artifact from ever being included by clasp.
await rm(new URL('../build/ArchitecturePoc.js', import.meta.url), { force: true });

await build({
  absWorkingDir: repositoryRoot,
  entryPoints: ['src/entrypoints/apps-script.ts'],
  outfile: 'build/Cockpit.js',
  bundle: true,
  format: 'iife',
  globalName: 'CockpitBundle',
  platform: 'neutral',
  target: 'es2020',
  treeShaking: true,
  minify: false,
  sourcemap: false,
  legalComments: 'none',
  banner: {
    js: '// Generated by npm run build:cockpit. Do not edit.'
  },
  footer: {
    js: [
      'function addSelectedToWatchlist() {',
      '  return CockpitBundle.addSelectedToWatchlist();',
      '}',
      '',
      'function createTradePlanFromSelectedWatchlist() {',
      '  return CockpitBundle.createTradePlanFromSelectedWatchlist();',
      '}',
      '',
      'function executeSelectedTradePlan() {',
      '  return CockpitBundle.executeSelectedTradePlan();',
      '}',
      '',
      'function closeSelectedPosition() {',
      '  return CockpitBundle.closeSelectedPosition();',
      '}',
      '',
      'function reconcileSelectedPosition() {',
      '  return CockpitBundle.reconcileSelectedPosition();',
      '}',
      '',
      'function setupTradingAccounts() {',
      '  return CockpitBundle.setupTradingAccounts();',
      '}'
    ].join('\n')
  }
});
